### ISSUE TITLE
点击归档展开出现滚动条的问题

### ISSUE THREAD

**Issue by lilonghe** [denjones/hexo-theme-chan#1]
滚动条会占用15px的空间，而且页面会抖动一下
我觉得这块你可以做的更好一点哦

**Comment by denjones** [comment]
你是屏幕高度不够吧，出现滚动条正常

**Comment by denjones** [comment]
0.1.3 侧边栏添加 perfect-scrollbar 支持
https://github.com/denjones/hexo-theme-chan/commit/cc193d3752781c338a4d6652adbc7409020cabd2
