### ISSUE TITLE
Howto setup category?

### ISSUE THREAD

**Issue by Troland** [denjones/hexo-theme-chan#2]
Hi, guy ,can you figure me out howto setup the category in the _config.yml?
I follow the scripts in the [official doc](https://hexo.io/docs/front-matter.html), while it still can't work.
Any help is appriated, thanks.

**Comment by denjones** [comment]
what category?

**Comment by methor** [comment]
It also happened to me. The category, tag and archive entries on the left panel don't expand&collapse at all. Tags and categories are shown normally in the main page.

**Comment by denjones** [comment]
Any error in console?

**Comment by methor** [comment]
I checked in the console, firefox console report "block loading mixed active content", that is http content in a https page. I manually release the block on that page and everything is ok. Is it possible to transform the mixed active content i.e. the javascript content into https?

**Comment by methor** [comment]
Plus, after reloading the page, http content is blocked again. It is quite annoying.

**Comment by denjones** [comment]
Fixed with commit dcdce1412598804733a40a363d6ce44a4b597acc
