### ISSUE TITLE
cannot format math expression

### ISSUE THREAD

**Issue by methor** [denjones/hexo-theme-chan#3]
I installed hexo-math plugin which supports mathjax with math block syntax 

> $$< latex-like math expr \>$$. 

Such block shows correctly under landscape theme, but incorrect under chan. What is the problem?

**Comment by denjones** [comment]
I think it's a bug of hexo-math https://github.com/akfish/hexo-math/issues/26
Or maybe you can use https://github.com/phoenixcw/hexo-renderer-mathjax instead.
